import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { organizations } from './organizations';
import { users } from './users';
import { patients } from './patients';
import { conversations } from './conversations';
import {
  caseActorRoleEnum,
  caseAssigneeRoleEnum,
  caseEventTypeEnum,
  caseStageEnum,
} from './case-enums';
import { conversationPriorityEnum } from './messaging-enums';

/**
 * cases
 *
 * The central Phase-5 entity. Each case binds:
 *   - one patient (1:1 at case-open time, can be re-bound on merge)
 *   - the source conversation (optional)
 *   - the target hospital(s) the agency is pursuing for this case
 *   - the agency's policy snapshot at open time (referral / deposit / commission)
 *
 * `policySnapshotJson` is the **policy-snapshot pattern** carried over from
 * Phase 1 plan: when a hospital later changes their referral rate, open cases
 * still compute settlement against the snapshotted policy. The snapshot is
 * frozen at case creation; only an explicit re-snapshot action (audit-logged)
 * can overwrite it.
 *
 * caseNumber is a human-friendly per-org identifier (`EM-2026-0001`),
 * generated by `lib/db/repositories/cases.ts` from a per-org+year sequence.
 */
export const cases = pgTable(
  'cases',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    patientId: uuid('patient_id')
      .notNull()
      .references(() => patients.id, { onDelete: 'restrict' }),
    sourceConversationId: uuid('source_conversation_id').references(() => conversations.id, {
      onDelete: 'set null',
    }),

    caseNumber: text('case_number').notNull(), // EM-2026-0001
    title: text('title').notNull(),            // "Ms. Wang — Rhinoplasty + Hair"

    stage: caseStageEnum('stage').notNull().default('scoping'),
    priority: conversationPriorityEnum('priority').notNull().default('normal'),

    // ── Targeting ─────────────────────────────────────────────────
    /** Hospital ids the agency is pursuing for RFQ (from `hospitals` table). */
    targetHospitalIdsJson: jsonb('target_hospital_ids_json')
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),
    /** Procedure categories of interest (procedure_category values). */
    targetProcedureCategoriesJson: jsonb('target_procedure_categories_json')
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),
    /** Specific procedure codes if known (otherwise category-only). */
    targetProcedureCodesJson: jsonb('target_procedure_codes_json')
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),

    // ── Travel dates ──────────────────────────────────────────────
    estimatedArrivalDate: text('estimated_arrival_date'),   // YYYY-MM-DD
    actualArrivalDate: text('actual_arrival_date'),
    estimatedDepartureDate: text('estimated_departure_date'),
    actualDepartureDate: text('actual_departure_date'),
    patientTimezone: text('patient_timezone'),

    // ── Financial summary (KRW minor units; recomputed on chart finalize) ──
    currency: text('currency').notNull().default('KRW'),
    estimatedTotalKrw: integer('estimated_total_krw'),
    actualTotalKrw: integer('actual_total_krw'),
    depositTotalKrw: integer('deposit_total_krw'),
    referralFeeTotalKrw: integer('referral_fee_total_krw'),

    // ── Policy snapshot ───────────────────────────────────────────
    /**
     * Frozen at case-open time. Shape:
     *   {
     *     snapshotAt: ISO timestamp,
     *     hospitalRates: { [hospitalId]: HospitalReferralRate[] },
     *     depositPolicies: { [hospitalId]: HospitalDepositPolicy },
     *     commissionPolicies: ...,    // Phase 6 expands
     *     fxRateKrwPer: { USD: 1340, ... },
     *   }
     */
    policySnapshotJson: jsonb('policy_snapshot_json')
      .$type<{
        snapshotAt: string;
        hospitalRates?: Record<string, unknown[]>;
        depositPolicies?: Record<string, unknown>;
        commissionPolicies?: unknown;
        fxRateKrwPer?: Record<string, number>;
      } | null>()
      .default(sql`null`),
    policySnapshotAt: timestamp('policy_snapshot_at', { withTimezone: true }),

    // ── Source / tags / outcome ───────────────────────────────────
    sourceChannel: text('source_channel'),
    sourceCampaign: text('source_campaign'),
    tagsJson: jsonb('tags_json').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default(sql`'{}'::jsonb`),

    closedAt: timestamp('closed_at', { withTimezone: true }),
    closedReason: text('closed_reason'),
    closedByUserId: uuid('closed_by_user_id').references(() => users.id, { onDelete: 'set null' }),

    // Pinned summary for the timeline header — denormalized count.
    eventsCount: integer('events_count').notNull().default(0),
    lastActivityAt: timestamp('last_activity_at', { withTimezone: true }).notNull().defaultNow(),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    createdByUserId: uuid('created_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (t) => ({
    orgStageIdx: index('cases_org_stage_idx').on(t.organizationId, t.stage),
    orgPatientIdx: index('cases_org_patient_idx').on(t.organizationId, t.patientId),
    orgArrivalIdx: index('cases_org_arrival_idx').on(t.organizationId, t.estimatedArrivalDate),
    orgLastActivityIdx: index('cases_org_last_activity_idx').on(
      t.organizationId,
      t.lastActivityAt,
    ),
    orgNumberUnique: uniqueIndex('cases_org_number_unique').on(t.organizationId, t.caseNumber),
  }),
);

export type Case = typeof cases.$inferSelect;
export type NewCase = typeof cases.$inferInsert;

/**
 * cases_counters
 *
 * Per-(org, year) monotonic counter for case-number generation. Bumped inside
 * the same transaction as the cases insert via `UPDATE … RETURNING value`,
 * which yields a fresh value with no race. Year rollover creates a new row.
 */
export const caseCounters = pgTable(
  'case_counters',
  {
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    year: integer('year').notNull(),
    value: integer('value').notNull().default(0),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    orgYearPk: uniqueIndex('case_counters_org_year_pk').on(t.organizationId, t.year),
  }),
);

/**
 * case_events
 *
 * Append-only timeline of everything that happened to a case. The patient
 * detail page (`app/agency/patients/[id]/page.tsx`) reads from this table to
 * render the "타임라인" card. Downstream phases append new event_type values
 * without ever updating existing rows.
 *
 * `relatedEntityType` + `relatedEntityId` form a polymorphic pointer to
 * conversation / message / quote / chart / payment / partner_booking, etc.
 * No FK is enforced — the related row may have been hard-deleted by a
 * compliance request while the event log must survive.
 */
export const caseEvents = pgTable(
  'case_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    caseId: uuid('case_id')
      .notNull()
      .references(() => cases.id, { onDelete: 'cascade' }),

    eventType: caseEventTypeEnum('event_type').notNull(),
    actorRole: caseActorRoleEnum('actor_role').notNull().default('agency'),
    actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),

    title: text('title').notNull(),
    description: text('description'),

    relatedEntityType: text('related_entity_type'),
    relatedEntityId: uuid('related_entity_id'),

    /** Stage transition payload: { from, to }. AI events: { jobId, confidenceBp }. */
    payloadJson: jsonb('payload_json')
      .$type<Record<string, unknown>>()
      .notNull()
      .default(sql`'{}'::jsonb`),

    /** When the event actually happened (may differ from createdAt for backfill). */
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    caseOccurredIdx: index('case_events_case_occurred_idx').on(t.caseId, t.occurredAt),
    orgOccurredIdx: index('case_events_org_occurred_idx').on(t.organizationId, t.occurredAt),
    relatedIdx: index('case_events_related_idx').on(t.relatedEntityType, t.relatedEntityId),
  }),
);

export type CaseEvent = typeof caseEvents.$inferSelect;
export type NewCaseEvent = typeof caseEvents.$inferInsert;

/**
 * case_assignees
 *
 * M:N — which users (and which roles) are assigned to a case. The primary
 * manager gets push/email notifications; observers see it in shared queues.
 * Distinct from `conversation_assignees` because a case may have multiple
 * conversations and additional roles (interpreter, driver) the conversation
 * model doesn't carry.
 */
export const caseAssignees = pgTable(
  'case_assignees',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    caseId: uuid('case_id')
      .notNull()
      .references(() => cases.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: caseAssigneeRoleEnum('role').notNull().default('primary_manager'),
    isActive: boolean('is_active').notNull().default(true),
    assignedAt: timestamp('assigned_at', { withTimezone: true }).notNull().defaultNow(),
    assignedById: uuid('assigned_by_id').references(() => users.id, { onDelete: 'set null' }),
    unassignedAt: timestamp('unassigned_at', { withTimezone: true }),
  },
  (t) => ({
    caseUserRoleUnique: uniqueIndex('case_assignees_case_user_role_unique').on(
      t.caseId,
      t.userId,
      t.role,
    ),
    caseIdx: index('case_assignees_case_idx').on(t.caseId, t.isActive),
    userActiveIdx: index('case_assignees_user_active_idx').on(t.userId, t.isActive),
  }),
);

export type CaseAssignee = typeof caseAssignees.$inferSelect;
export type NewCaseAssignee = typeof caseAssignees.$inferInsert;
