/**
 * 서울 30개 외국인 FIT 추천 호텔 — founder 2026-06-25 큐레이션.
 * 6개 권역 (강남/서초/건대/성수/명동/홍대) × 5개씩.
 *
 * 마스터 콘솔의 "서울 호텔 30종 일괄 등록" 버튼이 이 배열을 읽어
 * partner_listings 테이블에 category='hotel', status='approved' 로
 * 한 번에 insert. 같은 slug 가 있으면 skip (멱등).
 *
 * 각 행에 들어가는 정보:
 *   - 기본: title, description, locationLabel, priceWon (하한값),
 *     priceUnit='박', promoLabel (등급 또는 특이사항)
 *   - details: address (Google Maps 표시), grade, region,
 *     recommendedFor, imageKeywords (사진 큐레이션 힌트),
 *     seoTags (Open Graph / 검색 최적화)
 */

export type SeoulHotelSeed = {
  title: string;
  description: string;
  locationLabel: string;
  address: string;
  priceWon: number;
  /** 항상 '박' — 호텔 표준. */
  priceUnit: '박';
  promoLabel?: string;
  region: '강남' | '서초' | '건대' | '성수' | '명동' | '홍대';
  grade: '3성' | '4성' | '5성';
  recommendedFor: ReadonlyArray<string>;
  imageKeywords: ReadonlyArray<string>;
  seoTags: ReadonlyArray<string>;
};

export const SEOUL_HOTEL_PRODUCTS: ReadonlyArray<SeoulHotelSeed> = [
  // ─── 강남 (5) ─────────────────────────────────────────────
  {
    title: '파크 하얏트 서울 (Park Hyatt Seoul)',
    description: '강남 테헤란로 최고층에 위치한 5성급 럭셔리 호텔. 포브스 선정, 절제된 럭셔리 인테리어, 루프탑 수영장과 고급 스파를 갖춰 외국인 비즈니스 여행객이 최선호. 럭셔리 여행·비즈니스 출장에 추천. 1박 ₩450,000~700,000.',
    locationLabel: '강남구 테헤란로',
    address: '서울 강남구 테헤란로 606 파크 하얏트 서울',
    priceWon: 450_000,
    priceUnit: '박',
    promoLabel: '포브스 선정',
    region: '강남',
    grade: '5성',
    recommendedFor: ['럭셔리 여행', '비즈니스 출장'],
    imageKeywords: ['Park Hyatt Seoul', 'Tehran-ro skyline', 'rooftop pool', 'luxury suite', '강남 5성 호텔'],
    seoTags: ['강남 5성 호텔', '럭셔리 호텔 서울', 'Park Hyatt Seoul', '비즈니스 호텔', '포브스 호텔'],
  },
  {
    title: '그랜드 인터컨티넨탈 서울 파르나스 (Grand InterContinental Seoul Parnas)',
    description: '코엑스몰·별마당 도서관 바로 인근의 5성급 호텔. 수영장, 피트니스, 다국어 컨시어지를 갖춰 외국인 장기 체류에 인기. 쇼핑·관광·가족 여행에 추천. 1박 ₩350,000~550,000.',
    locationLabel: '강남구 삼성역',
    address: '서울 강남구 테헤란로 521 그랜드 인터컨티넨탈 서울 파르나스',
    priceWon: 350_000,
    priceUnit: '박',
    region: '강남',
    grade: '5성',
    recommendedFor: ['쇼핑·관광', '가족 여행', '장기 체류'],
    imageKeywords: ['Grand InterContinental Parnas', 'Samseong COEX', 'pool deck', 'family suite', '코엑스 호텔'],
    seoTags: ['삼성역 5성 호텔', '코엑스 호텔', 'InterContinental Seoul', '가족 호텔', '강남 럭셔리'],
  },
  {
    title: '조선 팰리스 서울 강남 (Josun Palace Seoul Gangnam)',
    description: '2021년 오픈한 5성급 럭셔리 컬렉션(메리어트) 신축 호텔. 전통과 현대를 결합한 디자인, 포브스 4성 등급. 인스타그램 감성 강남 럭셔리의 대표. 허니문·기념일·SNS 감성 여행에 추천. 1박 ₩400,000~650,000.',
    locationLabel: '강남구 도산대로',
    address: '서울 강남구 도산대로 317 조선 팰리스 서울 강남',
    priceWon: 400_000,
    priceUnit: '박',
    promoLabel: '메리어트 럭셔리 컬렉션',
    region: '강남',
    grade: '5성',
    recommendedFor: ['허니문', '기념일', 'SNS 감성 여행'],
    imageKeywords: ['Josun Palace Gangnam', 'Dosan-daero', 'Marriott Luxury Collection', 'honeymoon suite', '강남 신축 호텔'],
    seoTags: ['강남 5성 호텔', 'Josun Palace', 'Marriott', '허니문 호텔 서울', '감성 호텔'],
  },
  {
    title: '글래드 강남 코엑스센터 (Glad Gangnam COEX Center)',
    description: '코엑스 직결 4성 호텔. 무료 Wi-Fi, 수영장, 합리적인 4성급 가격대. 쇼핑·전시 목적의 외국인에게 최적 위치. 가족 여행에 추천. 1박 ₩180,000~280,000.',
    locationLabel: '강남구 영동대로',
    address: '서울 강남구 영동대로 513 글래드 강남 코엑스센터',
    priceWon: 180_000,
    priceUnit: '박',
    region: '강남',
    grade: '4성',
    recommendedFor: ['쇼핑', '전시회', '가족 여행'],
    imageKeywords: ['Glad Gangnam COEX', 'Yeongdong-daero', 'family room', 'pool', '코엑스 직결 호텔'],
    seoTags: ['코엑스 호텔', '강남 4성 호텔', 'Glad Hotel', '가성비 호텔', '전시 호텔'],
  },
  {
    title: '이비스 스타일 앰배서더 서울 강남 (ibis Styles Ambassador Seoul Gangnam)',
    description: '삼성역 도보 5분 역세권 3성 호텔. 깔끔한 인테리어, 무료 Wi-Fi, 영어 응대 완비. 가성비 강남의 대표 3성급. 백패커·솔로 여행·절약형 FIT에 추천. 1박 ₩120,000~180,000.',
    locationLabel: '강남구 봉은사로',
    address: '서울 강남구 봉은사로 375 이비스 스타일 앰배서더 서울 강남',
    priceWon: 120_000,
    priceUnit: '박',
    region: '강남',
    grade: '3성',
    recommendedFor: ['백패커', '솔로 여행', '절약형 FIT'],
    imageKeywords: ['ibis Styles Gangnam', 'Bongeunsa-ro', 'modern compact room', 'budget Seoul hotel'],
    seoTags: ['강남 3성 호텔', 'ibis 서울', '가성비 호텔', '삼성역 호텔', '백패커 호텔'],
  },

  // ─── 서초 (5) ─────────────────────────────────────────────
  {
    title: 'JW 메리어트 호텔 서울 (JW Marriott Hotel Seoul)',
    description: '고속터미널역 직결 5성급. 376실 규모, 우드파이어그릴 스테이크·정통 일식 타마유라·올데이다이닝 플레이버즈. 외국인 최상위 선호. 럭셔리 여행·미식 투어에 추천. 1박 ₩450,000~700,000.',
    locationLabel: '서초구 고속터미널역',
    address: '서울 서초구 신반포로 176 JW 메리어트 호텔 서울',
    priceWon: 450_000,
    priceUnit: '박',
    promoLabel: '고속터미널 직결',
    region: '서초',
    grade: '5성',
    recommendedFor: ['럭셔리 여행', '미식 투어'],
    imageKeywords: ['JW Marriott Seoul', 'Express Bus Terminal', 'fine dining', 'wood fire grill', '고속터미널 호텔'],
    seoTags: ['JW Marriott 서울', '서초 5성 호텔', '럭셔리 호텔', '고속터미널 호텔', '미식 호텔'],
  },
  {
    title: '쉐라톤 서울 팔래스 강남 (Sheraton Seoul Palace Gangnam)',
    description: '강남·서초 경계에 위치한 5성급 호텔. 클래식 럭셔리 인테리어, 수영장·스파 완비, 공항 접근 편리. 가족 여행·장기 체류에 추천. 1박 ₩300,000~480,000.',
    locationLabel: '서초구 남부순환로',
    address: '서울 서초구 남부순환로 2606 쉐라톤 서울 팔래스 강남',
    priceWon: 300_000,
    priceUnit: '박',
    region: '서초',
    grade: '5성',
    recommendedFor: ['가족 여행', '장기 체류'],
    imageKeywords: ['Sheraton Palace Gangnam', 'classic luxury', 'pool spa', '서초 5성'],
    seoTags: ['쉐라톤 서울', '서초 5성 호텔', 'Sheraton Palace', '가족 호텔', '강남 럭셔리'],
  },
  {
    title: '신라스테이 서초 (Shilla Stay Seocho)',
    description: '강남역·양재역 사이 역세권 4성. 허브 어메니티, 깔끔한 모던 인테리어. 출장과 관광을 겸하는 외국인 게스트에 최적. 비즈니스 출장·중장기 체류에 추천. 1박 ₩150,000~220,000.',
    locationLabel: '서초구 강남대로',
    address: '서울 서초구 강남대로 625 신라스테이 서초',
    priceWon: 150_000,
    priceUnit: '박',
    region: '서초',
    grade: '4성',
    recommendedFor: ['비즈니스 출장', '중장기 체류'],
    imageKeywords: ['Shilla Stay Seocho', 'modern business hotel', 'Hub amenity', '신라스테이 객실'],
    seoTags: ['신라스테이 서초', '서초 4성 호텔', '비즈니스 호텔', '강남역 호텔', '출장 호텔'],
  },
  {
    title: '노보텔 앰배서더 서울 강남 (Novotel Ambassador Seoul Gangnam)',
    description: '강남역 도보 3분 초역세권 4성 호텔. 수영장·피트니스, 영어 응대 완비. 외국인 장기 여행과 단기 출장에 모두 인기. 쇼핑·비즈니스·의료관광에 추천. 1박 ₩180,000~280,000.',
    locationLabel: '서초구 강남대로',
    address: '서울 강남구 강남대로 603 노보텔 앰배서더 서울 강남',
    priceWon: 180_000,
    priceUnit: '박',
    promoLabel: '강남역 도보 3분',
    region: '서초',
    grade: '4성',
    recommendedFor: ['쇼핑', '비즈니스', '의료관광'],
    imageKeywords: ['Novotel Ambassador Gangnam', 'Gangnam Station', 'pool gym', '강남역 호텔'],
    seoTags: ['Novotel 강남', '강남역 4성', '쇼핑 호텔', '의료관광 호텔', '비즈니스 호텔'],
  },
  {
    title: '임피리얼 팰리스 서울 (Imperial Palace Seoul)',
    description: '5성급 클래식 럭셔리. 헬스클럽, 실내·야외 수영장, 카지노까지 갖춰 중동·동남아 외국인 여행객이 선호. 그룹 여행·럭셔리 의료관광에 추천. 1박 ₩250,000~400,000.',
    locationLabel: '강남구 언주로',
    address: '서울 강남구 언주로 640 임피리얼 팰리스 서울',
    priceWon: 250_000,
    priceUnit: '박',
    promoLabel: '카지노 보유',
    region: '서초',
    grade: '5성',
    recommendedFor: ['그룹 여행', '럭셔리 의료관광'],
    imageKeywords: ['Imperial Palace Seoul', 'Eonju-ro', 'casino', 'indoor outdoor pool', '클래식 럭셔리'],
    seoTags: ['Imperial Palace', '강남 5성 호텔', '카지노 호텔', '의료관광 호텔', '중동 여행객'],
  },

  // ─── 건대 (5) ─────────────────────────────────────────────
  {
    title: '더 클래식 500 이그제큐티브 레지던스 펜타즈 (The Classic 500 Executive Residence Pentaz)',
    description: '건대입구역 도보 3분 4성급 최고급 레지던스형 호텔. 평점 8.8/10. 넓은 객실, 장기체류 최적, 건국대 병원 인근. 의료관광·장기 체류·가족 여행에 추천. 1박 ₩180,000~280,000.',
    locationLabel: '광진구 건대입구역',
    address: '서울 광진구 능동로 90 더 클래식 500 펜타즈',
    priceWon: 180_000,
    priceUnit: '박',
    promoLabel: '레지던스형 · 평점 8.8',
    region: '건대',
    grade: '4성',
    recommendedFor: ['의료관광', '장기 체류', '가족 여행'],
    imageKeywords: ['The Classic 500 Pentaz', 'Konkuk University', 'executive residence', '건대 레지던스'],
    seoTags: ['건대 4성 호텔', '레지던스 호텔', '건국대 병원 호텔', '장기 체류 호텔', '의료관광 호텔'],
  },
  {
    title: '호텔 더 디자이너스 프리미어 성수&건대 (Hotel The Designers Premier Seongsu & Konkuk)',
    description: '2023년 리뉴얼된 4성 호텔. 20층 라운지 야경, 세탁실 무료, 넷플릭스·OTT 완비. 성수동·건대 모두 도보권으로 트렌드 여행과 젊은 외국인 FIT에 최적. 1박 ₩130,000~200,000.',
    locationLabel: '성동구 건대-성수 사이',
    address: '서울 성동구 호텔 더 디자이너스 프리미어 성수 건대',
    priceWon: 130_000,
    priceUnit: '박',
    promoLabel: '2023년 리뉴얼',
    region: '건대',
    grade: '4성',
    recommendedFor: ['트렌드 여행', '젊은 외국인 FIT'],
    imageKeywords: ['Designers Premier Seongsu Konkuk', '20F lounge night view', 'OTT room', '디자인 호텔'],
    seoTags: ['건대 호텔', '성수 호텔', '디자인 호텔', '리뉴얼 호텔', '젊은 여행객'],
  },
  {
    title: '에이치에비뉴 호텔 건대 성수 (H Avenue Hotel Konkuk Seongsu)',
    description: '건대입구역 인근 3성 디자인 호텔. 세련된 인테리어, 성수동 카페거리·건대 먹자골목 도보 접근. 가성비 우수. 젊은 여행객·솔로 FIT에 추천. 1박 ₩100,000~160,000.',
    locationLabel: '광진구 건대입구역',
    address: '서울 광진구 능동로 에이치에비뉴 호텔 건대 성수',
    priceWon: 100_000,
    priceUnit: '박',
    region: '건대',
    grade: '3성',
    recommendedFor: ['젊은 여행객', '솔로 FIT'],
    imageKeywords: ['H Avenue Hotel Konkuk Seongsu', 'boutique design', 'Seongsu cafe street', '건대 부티크'],
    seoTags: ['건대 3성 호텔', 'H Avenue', '디자인 호텔', '성수 카페거리', '가성비 호텔'],
  },
  {
    title: '호텔 리베라 서울 (Hotel Riviera Seoul)',
    description: '건대·청담 중간에 위치한 4성 호텔. 수영장 보유, 쇼핑·나이트라이프 접근성 우수. 외국인 단체·가족 여행객 인기. 청담 쇼핑에 추천. 1박 ₩150,000~230,000.',
    locationLabel: '강남구 영동대로 (청담)',
    address: '서울 강남구 영동대로 737 호텔 리베라 서울',
    priceWon: 150_000,
    priceUnit: '박',
    region: '건대',
    grade: '4성',
    recommendedFor: ['가족 여행', '청담 쇼핑'],
    imageKeywords: ['Hotel Riviera Seoul', 'Cheongdam', 'pool', 'family suite', '청담 호텔'],
    seoTags: ['청담 호텔', '건대 인근 호텔', 'Hotel Riviera', '가족 호텔', '수영장 호텔'],
  },
  {
    title: '화양연화 서울 건대 (Hwa Yang Yeon Hwa Seoul Konkuk)',
    description: '한국 드라마 감성 인테리어의 3성 호텔. 다다미 객실, 한국 의상 비치. 외국인의 K-컬처 체험 숙소로 인기. K-드라마 팬·젊은 아시아 여행객에 추천. 1박 ₩90,000~140,000.',
    locationLabel: '광진구 건대입구역',
    address: '서울 광진구 화양동 화양연화 서울 건대',
    priceWon: 90_000,
    priceUnit: '박',
    promoLabel: 'K-드라마 감성',
    region: '건대',
    grade: '3성',
    recommendedFor: ['K-드라마 팬', '젊은 아시아 여행객'],
    imageKeywords: ['Hwa Yang Yeon Hwa', 'K-drama themed room', 'tatami', 'hanbok closet', '드라마 호텔'],
    seoTags: ['건대 K-호텔', 'K-드라마 호텔', '한복 체험 호텔', '감성 호텔', '아시아 여행객'],
  },

  // ─── 성수 (5) ─────────────────────────────────────────────
  {
    title: '언더스탠드 에비뉴 호텔 성수 (Understand Avenue Hotel Seongsu)',
    description: '성수동 카페거리·팝업스토어 밀집지역 도보권의 4성 호텔. 트렌디한 인테리어로 MZ와 외국인 감성 여행에 특화. 팝업·전시 방문객에 추천. 1박 ₩130,000~200,000.',
    locationLabel: '성동구 성수역',
    address: '서울 성동구 성수이로 언더스탠드 에비뉴 호텔 성수',
    priceWon: 130_000,
    priceUnit: '박',
    region: '성수',
    grade: '4성',
    recommendedFor: ['감성 여행', '팝업·전시 방문객'],
    imageKeywords: ['Understand Avenue Seongsu', 'pop-up store', 'design hotel', '성수 카페거리'],
    seoTags: ['성수 호텔', '디자인 호텔', '팝업 호텔', 'MZ 호텔', '감성 여행'],
  },
  {
    title: '목시 서울 성수 (Moxy Seoul Seongsu, 메리어트)',
    description: '메리어트 부티크 브랜드 Moxy 의 4성 호텔. 힙한 공용 라운지와 루프탑 바로 외국인 젊은 여행객 SNS 핫플. 트렌드 여행·2030 외국인에 추천. 1박 ₩150,000~230,000.',
    locationLabel: '성동구 성수동',
    address: '서울 성동구 성수동 목시 서울 성수',
    priceWon: 150_000,
    priceUnit: '박',
    promoLabel: '메리어트 Moxy',
    region: '성수',
    grade: '4성',
    recommendedFor: ['트렌드 여행', '2030 외국인'],
    imageKeywords: ['Moxy Seoul Seongsu', 'rooftop bar', 'hip lounge', 'Marriott boutique', '성수 호텔'],
    seoTags: ['Moxy Seoul', '성수 4성 호텔', '메리어트 부티크', '루프탑 호텔', 'MZ 호텔'],
  },
  {
    title: '오크우드 프리미어 코엑스 센터 (Oakwood Premier COEX Center)',
    description: '스타필드 코엑스 직결 5성 레지던스형 호텔. 피트니스·수영장 완비, 장기체류형 서비스 레지던스. 평점 9.1/10. 장기 체류·가족 여행·비즈니스에 추천. 1박 ₩280,000~420,000.',
    locationLabel: '강남구 삼성역',
    address: '서울 강남구 영동대로 521 오크우드 프리미어 코엑스 센터',
    priceWon: 280_000,
    priceUnit: '박',
    promoLabel: '레지던스형 · 평점 9.1',
    region: '성수',
    grade: '5성',
    recommendedFor: ['장기 체류', '가족 여행', '비즈니스'],
    imageKeywords: ['Oakwood Premier COEX', 'serviced residence', 'long stay', 'pool', '코엑스 레지던스'],
    seoTags: ['Oakwood 코엑스', '5성 레지던스', '장기 체류 호텔', '가족 호텔', '삼성역 호텔'],
  },
  {
    title: '로컬스티치 성수 (Localstitch Seongsu)',
    description: '3성 부티크 코리빙 호텔. 공용 주방·정원·라운지로 코리빙과 호텔이 결합된 콘셉트. 장기 여행자·디지털 노마드 외국인에 인기. 1박 ₩80,000~130,000.',
    locationLabel: '성동구 성수동 1가',
    address: '서울 성동구 성수동 1가 로컬스티치 성수',
    priceWon: 80_000,
    priceUnit: '박',
    promoLabel: '코리빙',
    region: '성수',
    grade: '3성',
    recommendedFor: ['디지털 노마드', '장기 체류 FIT'],
    imageKeywords: ['Localstitch Seongsu', 'co-living', 'shared kitchen', 'garden lounge', '성수 코리빙'],
    seoTags: ['Localstitch', '성수 코리빙', '디지털 노마드 호텔', '장기 체류', '부티크 호텔'],
  },
  {
    title: '라이즈 호텔 오토그래프 컬렉션 성수 (RYSE Hotel Autograph Collection · 성수)',
    description: '5성 메리어트 오토그래프 컬렉션. 아트·뮤직 테마 럭셔리 호텔로 루프탑 풀, 전시 갤러리, DJ 라운지를 갖춤. 아티스트·외국인 여행객 사이 극강 인기. 허니문에 추천. 1박 ₩300,000~500,000.',
    locationLabel: '마포구 양화로 (홍대·성수 연계)',
    address: '서울 마포구 양화로 130 라이즈 호텔',
    priceWon: 300_000,
    priceUnit: '박',
    promoLabel: '메리어트 오토그래프',
    region: '성수',
    grade: '5성',
    recommendedFor: ['아트·음악 여행', '허니문'],
    imageKeywords: ['RYSE Autograph', 'art music hotel', 'rooftop pool', 'DJ lounge', '예술 호텔'],
    seoTags: ['RYSE Hotel', '메리어트 오토그래프', '아트 호텔', '루프탑 풀 호텔', '허니문 호텔'],
  },

  // ─── 명동 (5) ─────────────────────────────────────────────
  {
    title: '롯데호텔 서울 (Lotte Hotel Seoul)',
    description: '명동 중심 5성 랜드마크 호텔. 롯데면세점 직결, 1,015개 객실, 실내 수영장·스파·5개 레스토랑. 외국인 방한 1순위 호텔. 쇼핑·럭셔리 관광·단체 여행에 추천. 1박 ₩350,000~600,000.',
    locationLabel: '중구 명동·을지로',
    address: '서울 중구 을지로 30 롯데호텔 서울',
    priceWon: 350_000,
    priceUnit: '박',
    promoLabel: '면세점 직결',
    region: '명동',
    grade: '5성',
    recommendedFor: ['쇼핑', '럭셔리 관광', '단체 여행'],
    imageKeywords: ['Lotte Hotel Seoul', 'Myeongdong landmark', 'duty free shop', 'indoor pool', '명동 랜드마크'],
    seoTags: ['롯데호텔 서울', '명동 5성 호텔', '면세점 호텔', '단체 호텔', '랜드마크 호텔'],
  },
  {
    title: '르 메르디앙 서울 명동 (Le Méridien Seoul Myeongdong)',
    description: '명동역 도보 7분 5성 호텔. 도시 뷰 객실, 24시간 컨시어지, 비즈니스 센터. 세련된 유럽풍 럭셔리. 럭셔리 여행·비즈니스에 추천. 1박 ₩350,000~550,000.',
    locationLabel: '중구 명동역',
    address: '서울 중구 삼일대로 310 르 메르디앙 서울 명동',
    priceWon: 350_000,
    priceUnit: '박',
    region: '명동',
    grade: '5성',
    recommendedFor: ['럭셔리 여행', '비즈니스'],
    imageKeywords: ['Le Meridien Myeongdong', 'European luxury', 'city view room', '24h concierge', '명동 5성'],
    seoTags: ['Le Meridien Seoul', '명동 5성 호텔', '럭셔리 호텔', '비즈니스 호텔', '유럽풍 호텔'],
  },
  {
    title: '롯데시티호텔 명동 (Lotte City Hotel Myeongdong)',
    description: '명동 도보권 4성 호텔. 롯데 브랜드 신뢰도, 조식 뷔페·피트니스. 일본·중국 여행객이 선호. 가족 여행·쇼핑 목적 FIT에 추천. 1박 ₩200,000~320,000.',
    locationLabel: '중구 명동',
    address: '서울 중구 삼일대로 362 롯데시티호텔 명동',
    priceWon: 200_000,
    priceUnit: '박',
    region: '명동',
    grade: '4성',
    recommendedFor: ['가족 여행', '쇼핑 목적 FIT'],
    imageKeywords: ['Lotte City Hotel Myeongdong', 'breakfast buffet', 'Lotte brand', '명동 4성'],
    seoTags: ['롯데시티호텔', '명동 4성 호텔', '롯데 브랜드', '쇼핑 호텔', '일본·중국 여행객'],
  },
  {
    title: '호텔28 명동 (Hotel28 Myeongdong)',
    description: '명동역 도보 3분 3성 호텔. 명동 중심가 위치, 한국 전통 조식, 따뜻한 직원 서비스. 해외 거주 교포·외국인 가족 여행에 극강 인기. 첫 방한 외국인에 추천. 1박 ₩130,000~200,000.',
    locationLabel: '중구 명동',
    address: '서울 중구 명동 호텔28 명동',
    priceWon: 130_000,
    priceUnit: '박',
    region: '명동',
    grade: '3성',
    recommendedFor: ['가족 여행', '첫 방한 외국인'],
    imageKeywords: ['Hotel28 Myeongdong', 'Korean breakfast', 'warm service', '명동 부티크 3성'],
    seoTags: ['호텔28 명동', '명동 3성 호텔', '교포 호텔', '가족 호텔', '첫 방한 호텔'],
  },
  {
    title: '솔라리아 니시테츠 호텔 서울 명동 (Solaria Nishitetsu Hotel Seoul Myeongdong)',
    description: '명동역 인근 3성 일본 체인 호텔. 청결도와 정갈함, 뷔페 조식 인기, 첨단 욕실 시설. 일본·동남아 여행객이 선호. 깔끔함을 중시하는 FIT에 추천. 1박 ₩120,000~190,000.',
    locationLabel: '중구 명동',
    address: '서울 중구 명동 솔라리아 니시테츠 호텔 서울 명동',
    priceWon: 120_000,
    priceUnit: '박',
    promoLabel: '일본 체인',
    region: '명동',
    grade: '3성',
    recommendedFor: ['일본 여행객', '깔끔함 중시 FIT'],
    imageKeywords: ['Solaria Nishitetsu Myeongdong', 'Japanese chain', 'spotless bathroom', '일본 호텔'],
    seoTags: ['Solaria Nishitetsu', '명동 3성 호텔', '일본 체인 호텔', '청결 호텔', '동남아 여행객'],
  },

  // ─── 홍대 (5) ─────────────────────────────────────────────
  {
    title: '아만티 서울 (Amanti Seoul)',
    description: '홍대입구역 1번 출구 500m 4성 호텔. 야외 수영장·피트니스 완비, 홍대 클럽·카페거리 도보 접근. 유럽 여행객이 선호하는 4성급. 나이트라이프 여행에 추천. 1박 ₩160,000~260,000.',
    locationLabel: '마포구 홍대입구역',
    address: '서울 마포구 양화로 아만티 서울',
    priceWon: 160_000,
    priceUnit: '박',
    region: '홍대',
    grade: '4성',
    recommendedFor: ['유럽·서양 FIT', '나이트라이프 여행'],
    imageKeywords: ['Amanti Seoul', 'Hongdae nightlife', 'outdoor pool', 'cafe street', '홍대 4성'],
    seoTags: ['Amanti Seoul', '홍대 4성 호텔', '나이트라이프 호텔', '유럽 여행객', '수영장 호텔'],
  },
  {
    title: '머큐어 앰배서더 서울 홍대 (Mercure Ambassador Seoul Hongdae)',
    description: '홍대입구역 인근 4성 글로벌 체인 호텔. 피트니스·정원·공용 라운지, 영어/다국어 직원. 비즈니스+관광 겸용의 유럽·미주 여행객에 추천. 1박 ₩170,000~270,000.',
    locationLabel: '마포구 홍대',
    address: '서울 마포구 양화로 머큐어 앰배서더 서울 홍대',
    priceWon: 170_000,
    priceUnit: '박',
    region: '홍대',
    grade: '4성',
    recommendedFor: ['비즈니스+관광', '유럽·미주 여행객'],
    imageKeywords: ['Mercure Ambassador Hongdae', 'Accor brand', 'garden lounge', '홍대 4성'],
    seoTags: ['Mercure Hongdae', '홍대 4성 호텔', 'Accor 호텔', '유럽·미주 여행객', '비즈니스 호텔'],
  },
  {
    title: '라이즈 호텔 오토그래프 컬렉션 홍대 (RYSE Hotel Autograph Collection · 홍대)',
    description: '홍대입구역 도보 10분 5성 메리어트 오토그래프 컬렉션. 아트·뮤직 테마, 루프탑 수영장·DJ 라운지·전시 갤러리. 외국인 아티스트·음악 팬의 성지. 허니문에 추천. 1박 ₩300,000~500,000.',
    locationLabel: '마포구 양화로',
    address: '서울 마포구 양화로 130 라이즈 호텔 홍대',
    priceWon: 300_000,
    priceUnit: '박',
    promoLabel: '메리어트 오토그래프',
    region: '홍대',
    grade: '5성',
    recommendedFor: ['아트·음악 여행', '허니문', '감성 FIT'],
    imageKeywords: ['RYSE Hongdae', 'Autograph Collection', 'art gallery', 'DJ lounge', 'rooftop pool', '홍대 럭셔리'],
    seoTags: ['RYSE Hotel 홍대', '메리어트 오토그래프', '홍대 5성 호텔', '아트 호텔', '허니문 호텔'],
  },
  {
    title: 'L7 홍대 바이 롯데 (L7 Hongdae by Lotte)',
    description: '홍대입구역 도보 5분 4성 라이프스타일 호텔. 롯데 라이프스타일 브랜드 L7, 루프탑 바·테라스·세련된 디자인. 홍대 야경 감상 포인트. 2030 감성 여행·커플·SNS 여행객에 추천. 1박 ₩180,000~280,000.',
    locationLabel: '마포구 양화로',
    address: '서울 마포구 양화로 141 L7 홍대',
    priceWon: 180_000,
    priceUnit: '박',
    promoLabel: '롯데 L7 라이프스타일',
    region: '홍대',
    grade: '4성',
    recommendedFor: ['2030 감성 여행', '커플', 'SNS 여행객'],
    imageKeywords: ['L7 Hongdae', 'Lotte lifestyle', 'rooftop terrace', 'night view', '홍대 야경'],
    seoTags: ['L7 Hongdae', '홍대 4성 호텔', '롯데 라이프스타일', '루프탑 호텔', '커플 호텔'],
  },
  {
    title: '필로소퍼 홍대 (Philosopher Hongdae)',
    description: '홍대입구역 도보 4분 3성 부티크 감성 호텔. 공용 라운지, 홍대 메인 거리 도보 접근, 예산형 외국인 솔로 여행자에 인기. 배낭여행·솔로 FIT·절약형 여행에 추천. 1박 ₩90,000~150,000.',
    locationLabel: '마포구 홍대입구역',
    address: '서울 마포구 홍대 필로소퍼 홍대',
    priceWon: 90_000,
    priceUnit: '박',
    region: '홍대',
    grade: '3성',
    recommendedFor: ['배낭여행', '솔로 FIT', '절약형 여행'],
    imageKeywords: ['Philosopher Hongdae', 'boutique budget', 'shared lounge', 'Hongdae main street', '홍대 부티크'],
    seoTags: ['Philosopher Hongdae', '홍대 3성 호텔', '부티크 호텔', '솔로 여행', '예산 호텔'],
  },
];
