/**
 * 서울 외국인 FIT 추천 파트너병원 24곳 — founder 2026-07-24 큐레이션.
 *
 * 정형외과·척추·관절(7) + 비뇨의학과(3) + 산부인과·여성의학(2) +
 * 이비인후과(2) + 내과·소화기(3) + 외과·화상·통증·재활·신경과·소아과(7).
 *
 * 마스터 콘솔의 "파트너병원 24종 일괄 등록" 버튼이 이 배열을 읽어
 * hospitals + category_listings + hospital_locale_content(KR/EN) 에
 * 카테고리='partner' (공개 /kr/clinics 칩 키와 동일) 로 upsert.
 * 각 병원의 실제 진료과는 specialty 필드 + description 에 기재.
 * SEO 브랜드는 GlowUpTour.
 */

export type PartnerSeed = {
  title: string;
  englishTitle: string;
  slug: string;
  /** 진료과 표기 (정형외과·비뇨의학과 등) */
  specialty: string;
  description: string;
  locationLabel: string;
  address: string;
  phone: string;
  nearestStation: string;
  signatureProcedures: ReadonlyArray<string>;
  procedureName: string;
  promoLabel: string;
  languagesSpoken: ReadonlyArray<'ko' | 'en' | 'zh' | 'ja' | 'ru' | 'ar' | 'mn' | 'vi'>;
  interpreterIncluded?: boolean;
  /** SEO 6종 — 브랜드 GlowUpTour */
  seoTitle: string;
  seoDescription: string;
  seoTags: ReadonlyArray<string>;
  ogDescription: string;
  imageKeywords: ReadonlyArray<string>;
};

export const PARTNER_PRODUCTS: ReadonlyArray<PartnerSeed> = [
  // ── 정형외과·척추·관절 (7곳) ─────────────────────────────────────
  {
    title: '연세사랑병원',
    englishTitle: 'Yonsei Sarang Hospital',
    slug: 'yonsei-sarang-joint-hospital-seocho',
    specialty: '정형외과·관절전문',
    description:
      '[정형외과·관절전문] 보건복지부 3회 연속 관절전문병원 인증 (서울 강남·서초권 유일). 3D 시뮬레이션 맞춤형 무릎 인공관절 수술 특화, 어깨·족부·줄기세포 연골치료·척추 비수술 진료. 정형외과·신경외과·마취통증의학과·내과 협진. 방배역·사당역 인근, 영어 상담 가능.',
    locationLabel: '서초 방배',
    address: '서울특별시 서초구 남부순환로 2205 (방배동)',
    phone: '1577-0050',
    nearestStation: '방배역 · 사당역',
    signatureProcedures: ['무릎 인공관절(3D 맞춤형)', '어깨 치료', '족부 치료', '줄기세포 연골치료', '척추 비수술'],
    procedureName: '3D 맞춤 인공관절·연골치료',
    promoLabel: '관절전문 3회 인증·3D 인공관절',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '연세사랑병원 | 서초 관절전문·3D 인공관절 | GlowUpTour',
    seoDescription: '방배동. 복지부 3회 연속 관절전문병원. 3D 맞춤 인공관절·줄기세포 연골치료. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['서초정형외과', '관절전문병원', '인공관절수술', '무릎수술', '줄기세포연골', 'knee replacement Korea', 'joint hospital Seoul', '외국인정형외과'],
    ogDescription: '서초 정형외과 | 연세사랑·관절전문 인증·3D 인공관절 — GlowUpTour',
    imageKeywords: ['Yonsei Sarang Hospital Bangbae', '3D knee replacement Korea', '연세사랑병원'],
  },
  {
    title: '강남세브란스 척추병원',
    englishTitle: 'Gangnam Severance Spine Hospital',
    slug: 'gangnam-severance-spine-hospital',
    specialty: '척추',
    description:
      '[척추] 국내 최초 대학병원 척추전문병원 (연세대 의대 부속). 신경외과+정형외과+재활의학과 협동진료로 척추질환 수술·비수술 치료. 아태지역 근육병 재활연구소 지정, 국제교육센터 지정 — 해외 의료진이 배우러 오는 병원. 매봉역·한티역 인근, 영어·중국어·일어 응대.',
    locationLabel: '강남 도곡',
    address: '서울특별시 강남구 언주로 211 (도곡동)',
    phone: '1599-6114',
    nearestStation: '매봉역 · 한티역',
    signatureProcedures: ['척추질환 수술', '비수술 치료', '신경외과+정형외과+재활 협동진료'],
    procedureName: '척추 수술·비수술 협동진료',
    promoLabel: '국내 최초 대학 척추전문',
    languagesSpoken: ['ko', 'en', 'zh', 'ja'],
    interpreterIncluded: true,
    seoTitle: '강남세브란스 척추병원 | 국내 최초 대학 척추전문 | GlowUpTour',
    seoDescription: '도곡동. 국내 최초 척추전문병원. 신경외과+정형외과+재활 협동진료. 국제교육센터. 다국어 응대. GlowUpTour에서 예약.',
    seoTags: ['강남척추병원', '척추전문병원', '허리디스크수술', '척추협착증', '대학병원척추', 'spine hospital Korea', 'back surgery Seoul', '외국인척추치료'],
    ogDescription: '강남 척추병원 | 세브란스·국내 최초·국제교육센터 — GlowUpTour',
    imageKeywords: ['Gangnam Severance Spine Hospital', 'first university spine hospital Korea', '강남세브란스 척추병원'],
  },
  {
    title: '강남베드로병원',
    englishTitle: 'Gangnam Bedro Hospital',
    slug: 'gangnam-bedro-spine-hospital',
    specialty: '척추·관절·뇌신경',
    description:
      '[척추·관절·뇌신경] 척추·관절·뇌신경 통합 진료 종합 전문병원. 양방향 척추내시경 수술 운영, 양재역 4번 출구 초역세권. 국제진료 시스템 보유로 러시아·몽골·중앙아시아 환자 다수. 영어·러시아어·몽골어 응대.',
    locationLabel: '서초 양재',
    address: '서울특별시 서초구 남부순환로 2633 (양재역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '양재역 4번 출구',
    signatureProcedures: ['척추 수술·비수술', '관절 치료', '뇌신경센터', '양방향 척추내시경'],
    procedureName: '양방향 척추내시경·뇌신경',
    promoLabel: '러시아어·몽골어 국제진료',
    languagesSpoken: ['ko', 'en', 'ru', 'mn'],
    interpreterIncluded: true,
    seoTitle: '강남베드로병원 | 양재역 척추·관절·뇌신경 | GlowUpTour',
    seoDescription: '양재역 4번 출구. 척추·관절·뇌신경 통합진료. 양방향 척추내시경. 러시아어·몽골어 응대. GlowUpTour에서 예약.',
    seoTags: ['강남척추병원', '양재역병원', '척추내시경', '관절치료', '뇌신경센터', 'endoscopic spine Korea', 'spine clinic Seoul', '외국인척추'],
    ogDescription: '서초 척추병원 | 베드로·척추내시경·러시아어 몽골어 응대 — GlowUpTour',
    imageKeywords: ['Gangnam Bedro Hospital Yangjae', 'biportal endoscopic spine Korea', '강남베드로병원'],
  },
  {
    title: '우리들병원 강남',
    englishTitle: 'Wooridul Spine Hospital Gangnam',
    slug: 'wooridul-spine-hospital-gangnam',
    specialty: '척추',
    description:
      '[척추] 세계적으로 알려진 척추 전문병원 브랜드. 최소침습 척추수술의 세계 표준을 만든 병원으로 해외 의료진 연수 다수. 국제환자센터 운영 — 중동·아시아 VIP 환자 유치 경험 풍부. 내시경 디스크 수술·비수술 치료. 학동역·강남구청역 인근, 영어·아랍어·중국어·일어 응대.',
    locationLabel: '강남 청담',
    address: '서울특별시 강남구 논현로 731 (청담동)',
    phone: '홈페이지 문의',
    nearestStation: '학동역 · 강남구청역',
    signatureProcedures: ['최소침습 척추수술', '내시경 디스크 수술', '비수술 치료'],
    procedureName: '최소침습 척추·내시경 디스크',
    promoLabel: '최소침습 세계 표준',
    languagesSpoken: ['ko', 'en', 'ar', 'zh', 'ja'],
    interpreterIncluded: true,
    seoTitle: '우리들병원 강남 | 세계적 최소침습 척추수술 | GlowUpTour',
    seoDescription: '청담동. 최소침습 척추수술 세계 표준 병원. 국제환자센터. 중동·아시아 VIP 다수. 다국어 응대. GlowUpTour에서 예약.',
    seoTags: ['강남척추병원', '우리들병원', '최소침습척추', '내시경디스크', '국제환자센터', 'Wooridul spine', 'minimally invasive spine Korea', '외국인척추'],
    ogDescription: '강남 척추병원 | 우리들·세계 표준 최소침습·국제환자센터 — GlowUpTour',
    imageKeywords: ['Wooridul Spine Hospital Gangnam', 'minimally invasive spine world standard', '우리들병원 강남'],
  },
  {
    title: '나누리병원 강남점',
    englishTitle: 'Nanoori Hospital Gangnam',
    slug: 'nanoori-spine-hospital-gangnam',
    specialty: '척추·관절',
    description:
      '[척추·관절] 보건복지부 지정 척추전문병원 네트워크의 강남점. 국제학술지 논문 다수 발표, 외국인 환자 유치 등록 기관. 척추 비수술·수술·관절·인공관절·도수재활까지 원스톱 재활 시스템. 학동역 인근, 영어·중국어·러시아어 응대.',
    locationLabel: '강남',
    address: '서울특별시 강남구 (학동역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '학동역 인근',
    signatureProcedures: ['척추 비수술·수술', '관절 치료', '인공관절', '도수재활'],
    procedureName: '척추·관절 원스톱 재활',
    promoLabel: '복지부 지정 척추전문',
    languagesSpoken: ['ko', 'en', 'zh', 'ru'],
    interpreterIncluded: true,
    seoTitle: '나누리병원 강남 | 척추전문·관절 원스톱 재활 | GlowUpTour',
    seoDescription: '강남 학동역 인근. 복지부 지정 척추전문병원. 척추·관절·재활 원스톱. 영·중·러 응대. GlowUpTour에서 예약.',
    seoTags: ['강남척추병원', '나누리병원', '척추전문병원', '관절치료', '도수재활', 'Nanoori hospital', 'spine specialty Korea', '외국인척추'],
    ogDescription: '강남 척추병원 | 나누리·복지부 지정·원스톱 재활 — GlowUpTour',
    imageKeywords: ['Nanoori Hospital Gangnam', 'spine specialty hospital Korea', '나누리병원 강남'],
  },
  {
    title: '청담튼튼병원',
    englishTitle: 'Cheongdam Teunteun Hospital',
    slug: 'cheongdam-teunteun-spine-hospital',
    specialty: '척추·관절·통증',
    description:
      '[척추·관절·통증] 전국 튼튼병원 네트워크의 청담점. 비수술 척추·관절 치료 중심 — 통증클리닉·도수치료·재활 운영. 청담 위치로 의료관광 접근성 우수. 영어 상담 가능.',
    locationLabel: '강남 청담',
    address: '서울특별시 강남구 청담동 (청담역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '청담역 인근',
    signatureProcedures: ['척추·관절 비수술 치료', '통증클리닉', '도수치료', '재활'],
    procedureName: '척추관절 비수술·통증',
    promoLabel: '척추관절 비수술 중심',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '청담튼튼병원 | 척추·관절 비수술 치료 | GlowUpTour',
    seoDescription: '청담동. 척추·관절 비수술 중심. 통증클리닉·도수치료·재활. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['청담병원', '척추비수술', '관절치료', '통증클리닉', '도수치료', 'non-surgical spine Korea', 'pain clinic Seoul', '외국인정형외과'],
    ogDescription: '청담 병원 | 튼튼·척추관절 비수술·통증 클리닉 — GlowUpTour',
    imageKeywords: ['Cheongdam Teunteun Hospital', 'non-surgical spine joint Korea', '청담튼튼병원'],
  },
  {
    title: 'SNU서울병원',
    englishTitle: 'SNU Seoul Hospital',
    slug: 'snu-seoul-foot-ankle-hospital-gangnam',
    specialty: '정형외과·족부·관절내시경',
    description:
      '[정형외과·족부·관절내시경] 서울대 의대 출신 정형외과 전문의진. 족부·발목 분야 국내 최고 수준으로 알려진 병원 — 무릎 관절내시경·어깨·스포츠 손상 치료. 스포츠 선수 재활 다수, 수술+재활 원스톱. 대모산입구역 인근, 영어 상담 가능.',
    locationLabel: '강남',
    address: '서울특별시 강남구 (대모산입구역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '대모산입구역 인근',
    signatureProcedures: ['족부·발목질환', '무릎 관절내시경', '어깨 치료', '스포츠 손상'],
    procedureName: '족부·발목·관절내시경',
    promoLabel: '족부·발목 국내 최고 수준',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: 'SNU서울병원 | 강남 족부·발목·관절내시경 전문 | GlowUpTour',
    seoDescription: '강남. 서울대 출신 전문의. 족부·발목 국내 최고 수준. 스포츠 손상·관절내시경. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남정형외과', '족부전문', '발목수술', '관절내시경', '스포츠재활', 'foot ankle surgery Korea', 'sports medicine Seoul', '외국인정형외과'],
    ogDescription: '강남 정형외과 | SNU서울·족부 발목 전문·스포츠 재활 — GlowUpTour',
    imageKeywords: ['SNU Seoul Hospital foot ankle', 'sports medicine Gangnam', 'SNU서울병원'],
  },
  // ── 비뇨의학과 (3곳) ─────────────────────────────────────────────
  {
    title: '스탠탑비뇨의학과의원',
    englishTitle: 'Stantop Urology Clinic',
    slug: 'stantop-urology-clinic-gangnam',
    specialty: '비뇨의학과',
    description:
      '[비뇨의학과] 국내 최대 규모급 남성의원, 강남구 의료관광 공식 등재. 최첨단 수술실·외국인 전용 회복실·VIP실 완비. 전문의 3명 경력 25년, 상담 환자 10만 명. 전립선비대증 수술·남성성형·발기부전·조루·남성갱년기·줄기세포·남성 지방흡입. 미국·영국·중국·태국·인도네시아·베트남 의료기관 협력, 보건복지부 장관상 수상 원장. 영어·중국어·베트남어·인니어 응대.',
    locationLabel: '강남',
    address: '서울특별시 강남구 (강남구 의료관광 공식 등재)',
    phone: '홈페이지 문의',
    nearestStation: '강남권',
    signatureProcedures: ['전립선비대증 수술', '남성성형수술', '발기부전·조루 치료', '남성갱년기', '줄기세포', '남성 지방흡입'],
    procedureName: '전립선·남성성형',
    promoLabel: '외국인 전용 회복실·VIP',
    languagesSpoken: ['ko', 'en', 'zh', 'vi'],
    interpreterIncluded: true,
    seoTitle: '스탠탑비뇨의학과 | 강남 남성의학·외국인 전용 회복실 | GlowUpTour',
    seoDescription: '강남구 의료관광 등재. 국내 최대급 남성의원. 외국인 전용 회복실·VIP실. 전립선·남성성형. 다국어 응대. GlowUpTour에서 예약.',
    seoTags: ['강남비뇨의학과', '남성의원', '전립선치료', '남성성형', '외국인비뇨기과', 'urology Korea', "men's clinic Seoul", '의료관광비뇨기과'],
    ogDescription: '강남 비뇨의학과 | 스탠탑·외국인 전용 회복실·6개국 협력 — GlowUpTour',
    imageKeywords: ['Stantop Urology Gangnam', 'VIP recovery room urology Korea', '스탠탑비뇨의학과'],
  },
  {
    title: '서울N비뇨기과 강남본점',
    englishTitle: 'Seoul N Urology Gangnam',
    slug: 'seoul-n-urology-gangnam-365',
    specialty: '비뇨의학과',
    description:
      '[비뇨의학과] 365일 연중무휴 진료 — 여행 중 응급 요로결석에 최적. 서울대 출신 전문의, 급성 통증 당일 치료 시스템. 요로결석 24시 치료·리줌(전립선비대증)·발기부전·확대수술·정관/포경수술. 강남역 인근, 영어 상담 가능.',
    locationLabel: '강남 역삼',
    address: '서울특별시 강남구 역삼동 (강남역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '강남역 인근',
    signatureProcedures: ['요로결석 24시 치료', '리줌(전립선비대증)', '발기부전 치료', '확대수술', '정관/포경수술'],
    procedureName: '요로결석 24시·전립선',
    promoLabel: '365일 요로결석 24시',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '서울N비뇨기과 강남 | 365일 요로결석 24시 | GlowUpTour',
    seoDescription: '강남역 인근. 365일 연중무휴. 요로결석 24시 당일치료. 서울대 출신 전문의. 여행 중 응급 대응. GlowUpTour에서 예약.',
    seoTags: ['강남비뇨기과', '요로결석치료', '365일진료', '24시비뇨기과', '전립선비대증', 'kidney stone Korea', 'urology emergency Seoul', '외국인비뇨기과'],
    ogDescription: '강남 비뇨기과 | 서울N·365일 무휴·요로결석 당일 치료 — GlowUpTour',
    imageKeywords: ['Seoul N Urology 365 Gangnam', 'kidney stone emergency Korea', '서울N비뇨기과'],
  },
  {
    title: '강남J비뇨기과',
    englishTitle: 'Gangnam J Urology',
    slug: 'gangnam-j-urology-hakdong',
    specialty: '비뇨의학과',
    description:
      '[비뇨의학과] 남성수술 특화 원장 직접 집도. 수술 상담 전문 시스템(Meet the Expert) 운영. 남성수술·확대·조루·발기부전·전립선 질환 진료. 학동로 203, 학동역 접근성 우수. 영어 상담 가능.',
    locationLabel: '강남 학동',
    address: '서울특별시 강남구 학동로 203',
    phone: '홈페이지 문의',
    nearestStation: '학동역 인근',
    signatureProcedures: ['남성수술', '확대수술', '조루·발기부전 치료', '전립선 질환'],
    procedureName: '남성수술·전립선',
    promoLabel: '남성수술 원장 직접 집도',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '강남J비뇨기과 | 학동역 남성수술 전문 | GlowUpTour',
    seoDescription: '학동로 203. 남성수술 특화 원장 직접 집도. 전립선·남성 기능 치료. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남비뇨기과', '남성수술', '학동역비뇨기과', '전립선치료', "men's surgery Korea", 'urology Seoul', '외국인비뇨기과'],
    ogDescription: '강남 비뇨기과 | J비뇨기과·남성수술 특화·원장 집도 — GlowUpTour',
    imageKeywords: ['Gangnam J Urology Hakdong', "men's surgery clinic Korea", '강남J비뇨기과'],
  },
  // ── 산부인과·여성의학 (2곳) ──────────────────────────────────────
  {
    title: '강남차병원',
    englishTitle: 'Gangnam CHA Hospital',
    slug: 'gangnam-cha-womens-hospital',
    specialty: '산부인과·여성종합',
    description:
      '[산부인과·여성종합] 1960년 차산부인과 모태, 보건복지부 지정 산부인과 전문병원 — 국내 대표 여성종합병원. 산과(자연분만·제왕절개)·부인과·시험관아기(IVF)·난임치료·로봇수술·유방갑상선센터·고위험임산부집중치료 운영. 산부인과 단일 국내 최다 로봇수술 5,000례, 시험관아기센터 세계적 명성으로 해외 난임 환자 다수 방문. OICU·NICU 완비. 차병원사거리, 영어·중국어·일어·러시아어·몽골어 국제진료팀.',
    locationLabel: '강남 역삼',
    address: '서울특별시 강남구 논현로 566 (역삼동, 차병원사거리)',
    phone: '02-3468-3000',
    nearestStation: '역삼역 · 선정릉역 인근',
    signatureProcedures: ['산과(자연분만·제왕절개)', '부인과', '시험관아기(IVF)', '난임치료', '로봇수술', '유방갑상선센터', '고위험임산부 집중치료'],
    procedureName: 'IVF·로봇수술·여성종합',
    promoLabel: 'IVF 세계적 명성·로봇 5,000례',
    languagesSpoken: ['ko', 'en', 'zh', 'ja', 'ru', 'mn'],
    interpreterIncluded: true,
    seoTitle: '강남차병원 | 역삼 여성종합·시험관아기 세계적 명성 | GlowUpTour',
    seoDescription: '차병원사거리. 산부인과 전문병원. 시험관아기·난임 세계적 명성. 로봇수술 5,000례. 5개국어 국제진료팀. GlowUpTour에서 예약.',
    seoTags: ['강남산부인과', '차병원', '시험관아기', '난임치료', 'IVF Korea', '여성병원', 'CHA fertility', 'robot surgery Seoul', '외국인산부인과'],
    ogDescription: '강남 산부인과 | 차병원·IVF 세계적 명성·5개국어 국제진료 — GlowUpTour',
    imageKeywords: ['Gangnam CHA Hospital', 'IVF center world class Korea', '강남차병원'],
  },
  {
    title: '차 여성의학연구소 강남',
    englishTitle: 'CHA Fertility Center Gangnam',
    slug: 'cha-fertility-center-gangnam',
    specialty: '난임·가임력보존',
    description:
      '[난임·가임력보존] 세계 최초 유리화 난자동결 임신 성공 등 난임 분야 세계적 연구 기관. 시험관아기(IVF)·인공수정·난자동결·가임력보존·남성난임·착상전 유전진단 운영. 해외 환자 전용 코디네이터, 난자은행·정자은행 보유, 국제 난임 학회 주도. 강남차병원 내, 영어·중국어·일어·러시아어 응대.',
    locationLabel: '강남 역삼',
    address: '서울특별시 강남구 논현로 566 강남차병원 내 (역삼동)',
    phone: '02-3468-3000',
    nearestStation: '역삼역 · 선정릉역',
    signatureProcedures: ['시험관아기(IVF)', '인공수정', '난자동결', '가임력보존', '남성난임', '착상전 유전진단'],
    procedureName: 'IVF·난자동결·가임력보존',
    promoLabel: '세계 최초 유리화 난자동결',
    languagesSpoken: ['ko', 'en', 'zh', 'ja', 'ru'],
    interpreterIncluded: true,
    seoTitle: '차 여성의학연구소 | 강남 난임·난자동결 세계적 연구소 | GlowUpTour',
    seoDescription: '강남차병원 내. 세계 최초 유리화 난자동결 성공. IVF·가임력보존·난자은행. 해외환자 코디네이터. GlowUpTour에서 예약.',
    seoTags: ['강남난임', '시험관아기', '난자동결', '가임력보존', 'IVF Korea', 'egg freezing Seoul', 'fertility center Korea', '외국인난임치료'],
    ogDescription: '강남 난임센터 | 차 여성의학연구소·세계 최초 기록·난자은행 — GlowUpTour',
    imageKeywords: ['CHA Fertility Center Gangnam', 'egg freezing world first Korea', '차 여성의학연구소'],
  },
  // ── 이비인후과 (2곳) ─────────────────────────────────────────────
  {
    title: '하나이비인후과병원',
    englishTitle: 'Hana ENT Hospital',
    slug: 'hana-ent-hospital-gangnam',
    specialty: '이비인후과 전문병원',
    description:
      '[이비인후과 전문병원] 보건복지부 지정 이비인후과 전문병원 (강남 소재). 코·귀·목 전 분야 수술 가능한 병원급 시설 — 비중격만곡증·축농증·코물혹·비염·편도수술·어지럼증·코골이·수면무호흡·음성질환. 수면센터·음성센터 운영, 20대 이상 무료 주차. 역삼역 인근, 영어 상담 가능.',
    locationLabel: '강남 역삼',
    address: '서울특별시 강남구 역삼로 245 (역삼동)',
    phone: '홈페이지 문의',
    nearestStation: '역삼역 인근',
    signatureProcedures: ['비중격만곡증', '축농증·코물혹', '비염', '편도수술', '어지럼증', '코골이·수면무호흡', '음성질환'],
    procedureName: '축농증·코골이·수면무호흡',
    promoLabel: '복지부 지정 ENT 전문병원',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '하나이비인후과병원 | 역삼 이비인후과 전문병원 | GlowUpTour',
    seoDescription: '역삼로 245. 복지부 지정 이비인후과 전문병원. 축농증·코골이·수면무호흡 수술. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남이비인후과', '이비인후과전문병원', '축농증수술', '코골이치료', '수면무호흡', 'ENT hospital Korea', 'sinus surgery Seoul', '외국인이비인후과'],
    ogDescription: '강남 이비인후과 | 하나·전문병원 인증·수면센터 운영 — GlowUpTour',
    imageKeywords: ['Hana ENT Hospital Gangnam', 'sleep center ENT Korea', '하나이비인후과병원'],
  },
  {
    title: '강남코아이비인후과',
    englishTitle: 'Gangnam Coa ENT Clinic',
    slug: 'gangnam-coa-ent-clinic',
    specialty: '이비인후과',
    description:
      '[이비인후과] 코 질환 특화 이비인후과. "내 가족을 돌보는 마음" 진료 철학, 세밀한 진단 장비 완비. 코질환·비염·축농증·중이염·인후질환 진료. 영어 상담 가능.',
    locationLabel: '강남',
    address: '서울특별시 강남구 (강남 소재)',
    phone: '홈페이지 문의',
    nearestStation: '강남권',
    signatureProcedures: ['코질환', '비염', '축농증', '중이염', '인후질환'],
    procedureName: '코질환·비염 특화',
    promoLabel: '코질환 특화',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '강남코아이비인후과 | 코질환·비염 특화 | GlowUpTour',
    seoDescription: '강남. 코질환 특화 이비인후과. 비염·축농증·중이염. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남이비인후과', '비염치료', '축농증', '코질환전문', 'rhinitis treatment Korea', 'ENT Seoul', '외국인이비인후과'],
    ogDescription: '강남 이비인후과 | 코아·코질환 특화 진료 — GlowUpTour',
    imageKeywords: ['Gangnam Coa ENT Clinic', 'nose specialist clinic Korea', '강남코아이비인후과'],
  },
  // ── 내과·소화기 (3곳) ────────────────────────────────────────────
  {
    title: '강남탑내과',
    englishTitle: 'Gangnam Top Internal Medicine',
    slug: 'gangnam-top-internal-medicine-seocho',
    specialty: '내과·내시경',
    description:
      '[내과·내시경] 서초 내시경 특화 내과. 위·대장내시경 및 초음파 검사 원스톱, 직장인 검진 특화로 빠른 예약·검사 시스템. 소화기 질환 진료. 양재역·강남역 인근, 영어 상담 가능.',
    locationLabel: '서초',
    address: '서울특별시 서초구 효령로 431, 2층',
    phone: '1660-1776',
    nearestStation: '양재역 · 강남역 인근',
    signatureProcedures: ['위내시경', '대장내시경', '초음파 검사', '직장인 건강검진', '소화기 질환'],
    procedureName: '위대장내시경·검진',
    promoLabel: '내시경 원스톱',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '강남탑내과 | 서초 위대장내시경·검진 내과 | GlowUpTour',
    seoDescription: '서초 효령로. 위·대장내시경 특화. 초음파·직장인 검진 원스톱. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['서초내과', '위내시경', '대장내시경', '강남내과', '직장인검진', 'endoscopy Korea', 'gastroenterology Seoul', '외국인내과'],
    ogDescription: '서초 내과 | 강남탑·내시경 특화·원스톱 검사 — GlowUpTour',
    imageKeywords: ['Gangnam Top Internal Medicine Seocho', 'endoscopy clinic Korea', '강남탑내과'],
  },
  {
    title: '강남지인병원',
    englishTitle: 'Gangnam Giein Hospital',
    slug: 'gangnam-giein-hospital-nonhyeon',
    specialty: '내과·종합검진',
    description:
      '[내과·종합검진] 병원급 내과·검진 기관. 위·대장내시경·뇌 MRI/MRA·암표지자 검사·건강나이 분석·종합검진 운영. 수면내시경 수면비 미청구 등 투명한 비용 정책, 대장약 알약 처방 등 환자 편의 중심. 암 6종·질환 4종 예측 프로그램 보유. 학동역·언주역 인근, 영어 상담 가능.',
    locationLabel: '강남 논현',
    address: '서울특별시 강남구 언주로 631 (논현동 218-11)',
    phone: '02-6985-4119',
    nearestStation: '학동역 · 언주역 인근',
    signatureProcedures: ['위·대장내시경', '뇌 MRI/MRA', '암표지자 검사', '건강나이 분석', '종합검진'],
    procedureName: '내시경·뇌검진',
    promoLabel: '내시경+뇌검진·투명 비용',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '강남지인병원 | 논현 내시경·뇌검진 내과 | GlowUpTour',
    seoDescription: '언주로 631. 위대장내시경·뇌 MRI·암표지자. 투명한 비용 정책. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남내과', '내시경병원', '뇌MRI검사', '암표지자검사', '종합검진', 'brain MRI Korea', 'endoscopy Seoul', '외국인내과'],
    ogDescription: '강남 내과 | 지인병원·내시경+뇌검진·투명 비용 — GlowUpTour',
    imageKeywords: ['Gangnam Giein Hospital Nonhyeon', 'brain MRI checkup Korea', '강남지인병원'],
  },
  {
    title: '속편한내과 강남점',
    englishTitle: 'Sokpyeonhan Internal Medicine Gangnam',
    slug: 'sokpyeonhan-gastro-clinic-gangnam',
    specialty: '소화기내과',
    description:
      '[소화기내과] 전국 소화기 특화 내과 네트워크의 강남점. 소화기내시경 세부전문의 진료, 당일 내시경 시스템. 위·대장내시경·과민성대장·역류성식도염 진료. 강남역 인근, 영어 상담 가능.',
    locationLabel: '강남',
    address: '서울특별시 강남구 (강남역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '강남역 인근',
    signatureProcedures: ['위·대장내시경', '소화기 질환', '과민성대장', '역류성식도염'],
    procedureName: '당일 내시경·소화기',
    promoLabel: '당일 내시경',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '속편한내과 강남 | 소화기·당일 내시경 | GlowUpTour',
    seoDescription: '강남역 인근. 소화기 특화 네트워크. 세부전문의 내시경·역류성식도염 치료. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남내과', '소화기내과', '당일내시경', '역류성식도염', '과민성대장', 'gastroenterology Korea', 'same day endoscopy Seoul', '외국인내과'],
    ogDescription: '강남 내과 | 속편한·소화기 특화·당일 내시경 — GlowUpTour',
    imageKeywords: ['Sokpyeonhan gastro clinic Gangnam', 'same day endoscopy Korea', '속편한내과 강남'],
  },
  // ── 외과·화상·통증·재활·신경과·소아과 (7곳) ──────────────────────
  {
    title: '기쁨병원',
    englishTitle: 'Gippeum Hospital',
    slug: 'gippeum-hernia-surgery-hospital-gangnam',
    specialty: '외과·탈장·대장항문',
    description:
      '[외과·탈장·대장항문] 탈장 수술 국내 최다 수준 외과 전문병원. 인공막 없는 탈장수술법 자체 개발로 유명. 치질·대장항문·담석·복강경 수술 운영, 외과 단일 분야 특화 병원급 시설. 강남 논현로, 영어 상담 가능.',
    locationLabel: '강남',
    address: '서울특별시 강남구 논현로 (강남 소재)',
    phone: '홈페이지 문의',
    nearestStation: '강남권',
    signatureProcedures: ['탈장 무인공막 수술', '치질 수술', '대장항문', '담석', '복강경 수술'],
    procedureName: '무인공막 탈장수술',
    promoLabel: '탈장 국내 최다·무인공막',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '기쁨병원 | 강남 탈장·대장항문 외과 전문 | GlowUpTour',
    seoDescription: '강남 논현로. 탈장수술 국내 최다 수준. 무인공막 수술법 개발. 치질·담석·복강경. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남외과', '탈장수술', '치질수술', '대장항문', '복강경수술', 'hernia surgery Korea', 'colorectal Seoul', '외국인외과'],
    ogDescription: '강남 외과 | 기쁨병원·탈장 국내 최다·무인공막 수술 — GlowUpTour',
    imageKeywords: ['Gippeum Hospital hernia Gangnam', 'mesh-free hernia surgery Korea', '기쁨병원'],
  },
  {
    title: '베스티안 서울병원',
    englishTitle: 'Bestian Seoul Hospital',
    slug: 'bestian-burn-hospital-seoul',
    specialty: '화상·상처 전문',
    description:
      '[화상·상처 전문] 국내 대표 화상 전문병원 네트워크의 서울점. 급성 화상부터 흉터 재건까지 원스톱 — 화상 치료·화상 흉터 재건·상처 치료·흉터 성형. 화상 후 피부재건 성형 특화로 흉터 치료 목적 의료관광 수요 높음. 강남 논현동, 영어 상담 가능.',
    locationLabel: '강남 논현',
    address: '서울특별시 강남구 (논현동 소재)',
    phone: '홈페이지 문의',
    nearestStation: '강남권',
    signatureProcedures: ['화상 치료', '화상 흉터 재건', '상처 치료', '흉터 성형'],
    procedureName: '화상·흉터 재건',
    promoLabel: '화상 전문·흉터 재건',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '베스티안 서울 | 강남 화상·흉터 재건 전문 | GlowUpTour',
    seoDescription: '강남 논현동. 국내 대표 화상 전문병원. 급성 화상~흉터 재건 원스톱. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['화상전문병원', '화상치료', '흉터재건', '상처치료', '강남화상', 'burn center Korea', 'scar treatment Seoul', '외국인화상치료'],
    ogDescription: '강남 화상병원 | 베스티안·화상 전문·흉터 재건 원스톱 — GlowUpTour',
    imageKeywords: ['Bestian Seoul burn hospital', 'burn scar reconstruction Korea', '베스티안 서울병원'],
  },
  {
    title: '안강병원',
    englishTitle: 'Ahn Kang Hospital',
    slug: 'ahnkang-pain-hospital-gangnam',
    specialty: '통증의학·비수술 척추',
    description:
      '[통증의학·비수술 척추] 비수술 통증 치료 분야 국내 유명 병원. FIMS(기능적 근육내 자극술) 시술 특화. 수술 없이 만성통증·디스크를 치료하려는 해외 환자 수요 높음. 강남 소재, 영어 상담 가능.',
    locationLabel: '강남',
    address: '서울특별시 강남구 (강남 소재)',
    phone: '홈페이지 문의',
    nearestStation: '강남권',
    signatureProcedures: ['비수술 척추 치료', 'FIMS(기능적 근육내 자극술)', '만성통증 치료', '디스크 비수술'],
    procedureName: 'FIMS·비수술 통증',
    promoLabel: 'FIMS 비수술 통증',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '안강병원 | 강남 비수술 통증·FIMS 전문 | GlowUpTour',
    seoDescription: '강남. 비수술 척추·만성통증 유명 병원. FIMS 시술 특화. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남통증의학과', '비수술척추', 'FIMS', '만성통증치료', '디스크비수술', 'pain management Korea', 'non-surgical disc Seoul', '외국인통증치료'],
    ogDescription: '강남 통증병원 | 안강·비수술 척추·FIMS 특화 — GlowUpTour',
    imageKeywords: ['Ahn Kang Hospital FIMS', 'non-surgical pain Korea', '안강병원'],
  },
  {
    title: '연세베스트정형외과재활의학과',
    englishTitle: 'Yonsei Best Ortho & Rehab',
    slug: 'yonsei-best-rehab-clinic-bangbae',
    specialty: '재활의학',
    description:
      '[재활의학] 정형외과+재활의학과 결합 의원. 수술 후 재활·스포츠 재활 특화 — 재활치료·도수치료·체외충격파·근골격 초음파. 방배 지역 재활 거점. 방배역 인근, 영어 상담 가능.',
    locationLabel: '서초 방배',
    address: '서울특별시 서초구 방배동 (방배역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '방배역 인근',
    signatureProcedures: ['재활치료', '도수치료', '체외충격파', '스포츠 재활', '근골격 초음파'],
    procedureName: '도수치료·스포츠 재활',
    promoLabel: '도수·스포츠 재활 특화',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '연세베스트정형외과재활의학과 | 방배 재활·도수치료 | GlowUpTour',
    seoDescription: '서초 방배동. 정형외과+재활의학 결합. 도수치료·체외충격파·스포츠 재활. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['서초재활의학과', '도수치료', '체외충격파', '스포츠재활', '수술후재활', 'rehabilitation Korea', 'physical therapy Seoul', '외국인재활'],
    ogDescription: '서초 재활의학과 | 연세베스트·도수치료·스포츠 재활 — GlowUpTour',
    imageKeywords: ['Yonsei Best rehab Bangbae', 'sports rehabilitation Korea', '연세베스트재활'],
  },
  {
    title: '미래신경과의원',
    englishTitle: 'Mirae Neurology Clinic',
    slug: 'mirae-neurology-clinic-bangbae',
    specialty: '신경과',
    description:
      '[신경과] 서초 지역 신경과 전문의원. 두통·어지럼증 정밀 진단, 뇌졸중 위험 평가 및 예방 관리. 수면장애·말초신경질환 진료. 방배역 인근, 영어 상담 가능.',
    locationLabel: '서초 방배',
    address: '서울특별시 서초구 방배3동 (방배역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '방배역 인근',
    signatureProcedures: ['두통 치료', '어지럼증', '뇌졸중 예방', '수면장애', '말초신경질환'],
    procedureName: '두통·어지럼증·뇌졸중 예방',
    promoLabel: '두통·어지럼증 정밀 진단',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '미래신경과 | 방배 두통·어지럼증·뇌졸중 예방 | GlowUpTour',
    seoDescription: '서초 방배동. 두통·어지럼증 정밀 진단. 뇌졸중 예방 관리. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['서초신경과', '두통치료', '어지럼증', '뇌졸중예방', '수면장애', 'neurology Korea', 'headache clinic Seoul', '외국인신경과'],
    ogDescription: '서초 신경과 | 미래·두통 어지럼증·뇌졸중 예방 — GlowUpTour',
    imageKeywords: ['Mirae Neurology Bangbae', 'headache dizziness clinic Korea', '미래신경과'],
  },
  {
    title: '연세곰돌이소아청소년과',
    englishTitle: 'Yonsei Gomdori Pediatrics',
    slug: 'yonsei-gomdori-pediatrics-daechi',
    specialty: '소아청소년과',
    description:
      '[소아청소년과] 대치동 학부모 사이 인지도 높은 소아청소년과. 꼼꼼한 진료로 유명 — 소아 진료·예방접종·성장 관리·영유아 검진. 외국인 가족·주재원 자녀 예방접종·검진에 적합. 대치역 인근, 영어 상담 가능.',
    locationLabel: '강남 대치',
    address: '서울특별시 강남구 대치동 (대치역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '대치역 인근',
    signatureProcedures: ['소아 진료', '예방접종', '성장 관리', '영유아 검진'],
    procedureName: '소아진료·예방접종',
    promoLabel: '외국인 가족 소아진료 적합',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '연세곰돌이소아청소년과 | 대치동 소아진료·예방접종 | GlowUpTour',
    seoDescription: '강남 대치동. 소아진료·예방접종·성장관리. 외국인 가족 적합. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남소아과', '대치동소아과', '예방접종', '영유아검진', '성장관리', 'pediatrics Korea', 'vaccination Seoul', '외국인소아과'],
    ogDescription: '강남 소아과 | 곰돌이·예방접종·외국인 가족 적합 — GlowUpTour',
    imageKeywords: ['Yonsei Gomdori Pediatrics Daechi', 'kids clinic vaccination Korea', '연세곰돌이소아과'],
  },
  {
    title: '제일정형외과병원',
    englishTitle: 'Cheil Orthopedic Hospital',
    slug: 'cheil-orthopedic-hospital-sinsa',
    specialty: '정형외과',
    description:
      '[정형외과] 강남 신사 소재 정형외과 전문병원. 척추·관절 수술 및 비수술 통합 치료 — 인공관절·스포츠 손상 진료. 병원급 입원 시설 보유. 신사역 인근, 영어 상담 가능.',
    locationLabel: '강남 신사',
    address: '서울특별시 강남구 신사동 (신사역 인근)',
    phone: '홈페이지 문의',
    nearestStation: '신사역 인근',
    signatureProcedures: ['척추·관절 수술', '비수술 치료', '인공관절', '스포츠 손상'],
    procedureName: '척추·관절 통합 치료',
    promoLabel: '척추관절 통합·입원 가능',
    languagesSpoken: ['ko', 'en'],
    interpreterIncluded: true,
    seoTitle: '제일정형외과병원 | 신사 척추·관절 전문 | GlowUpTour',
    seoDescription: '강남 신사동. 척추·관절 수술+비수술 통합. 입원 시설 보유. 영어 상담. GlowUpTour에서 예약.',
    seoTags: ['강남정형외과', '신사정형외과', '척추수술', '인공관절', '스포츠손상', 'orthopedic hospital Korea', 'joint surgery Seoul', '외국인정형외과'],
    ogDescription: '강남 정형외과 | 제일·척추 관절 통합·입원 가능 — GlowUpTour',
    imageKeywords: ['Cheil Orthopedic Hospital Sinsa', 'spine joint hospital Korea', '제일정형외과병원'],
  },
];
